### ISSUE TITLE
[Question] Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/ling/Label 

### ISSUE THREAD

**Issue by heathersherry** [uma-pi1/minie#2]
Hi,
I come across a problem when trying to compile and run the Demo in Linux.
Here are my steps:

1. mvn clean install (in the main directory)
2. mvn dependency:copy-dependencies
3. cd target/
java -cp minie-0.0.1-SNAPSHOT.jar:dependency tests.minie.Demo

Here are the information I received:
Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/ling/Label
	at tests.minie.Demo.main(Demo.java:15)
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.ling.Label
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 1 more

May I know whether I have made any mistake? Thanks a lot for your time and help!

**Comment by heathersherry** [comment]
> Hi,
> I come across a problem when trying to compile and run the Demo in Linux.
> Here are my steps:
> 
> 1. mvn clean install (in the main directory)
> 2. mvn dependency:copy-dependencies
> 3. cd target/
>    java -cp minie-0.0.1-SNAPSHOT.jar:dependency tests.minie.Demo
> 
> Here are the information I received:
> Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/ling/Label
> at tests.minie.Demo.main(Demo.java:15)
> Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.ling.Label
> at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
> at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
> ... 1 more
> 
> May I know whether I have made any mistake? Thanks a lot for your time and help!

I fixed this issue by add all the jar files I need behind the command. Thanks a lot.

**Comment by heathersherry** [comment]
May I ask another question? I would like to use the MinIE-Dictionary mode, and want to download "Dictionary: Wikipedia: frequent relations and arguments". However, the hyperlink you provide for download (http://dws.informatik.uni-mannheim.de/fileadmin/lehrstuehle/pi1/pi1/minie/wiki-freq-args-rels.zip) is no longer accessible. 
Could you please fix this problem? Thanks a lot for your help!
