### ISSUE TITLE
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project minie: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java are missing or invalid -> [Help 1]

### ISSUE THREAD

**Issue by calbee633810** [uma-pi1/minie#5]
Dear authors,

When I tried to run the java project I came across some errors. 
Here are the steps I have taken:
1. `mvn clean install` (Success)
2. `mvn compile` (Success)
3. `mvn exec:java` (Build Failure)
The error message is:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< de.uni_mannheim:minie >------------------------
[INFO] Building minie 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ minie ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.704 s
[INFO] Finished at: 2019-10-28T14:33:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project minie: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java are missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```

I change to `mvn exec:java -Dexec.mainClass="test.main.Demo"` and there is still the same error.

Could you please give some hints for solving this problem? Thanks a lot.

**Comment by gkiril** [comment]
Try building a jar with ` mvn clean compile assembly:single`. This will create a jar: /target/minie-0.0.1-SNAPSHOT.jar. See how to use MinIE on the command line by running: `java -jar minie-0.0.1-SNAPSHOT.jar -h`.

**Comment by gkiril** [comment]
Alternatively, try this SO solution: https://stackoverflow.com/questions/40004614/maven-project-not-building?rq=1

**Comment by calbee633810** [comment]
Thanks a lot for the reply!

I tried the first solution,
1. mvn clean install (Success)
2. mvn clean compile assembly:single (Success)
3. cd target
4. java -jar minie-0.0.1-SNAPSHOT.jar (I would like to try reading from stdin and writing to stdout)
There is still failure message as follows.

```
root@xxx:/xxx/minie/target# java -jar minie-0.0.1-SNAPSHOT.jar   
Oct 29, 2019 7:12:41 AM de.uni_mannheim.minie.main.Main main
INFO: Setting up input and output streams...
Oct 29, 2019 7:12:42 AM de.uni_mannheim.minie.main.Main getInputStream
INFO: Reading from stdin
Oct 29, 2019 7:12:42 AM de.uni_mannheim.minie.main.Main getOutputStream
INFO: Writing to stdout
Oct 29, 2019 7:12:42 AM de.uni_mannheim.minie.main.Main main
INFO: Mode set to SAFE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 29, 2019 7:12:45 AM de.jollyday.util.XMLUtil unmarshallConfiguration
WARNING: Could not create JAXB context using the current threads context classloader. Defaulting to ObjectFactory classloader.
Exception in thread "main" edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
	at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:40)
	at edu.stanford.nlp.time.TimeExpressionExtractorFactory.create(TimeExpressionExtractorFactory.java:57)
	at edu.stanford.nlp.time.TimeExpressionExtractorFactory.createExtractor(TimeExpressionExtractorFactory.java:38)
	at edu.stanford.nlp.ie.regexp.NumberSequenceClassifier.<init>(NumberSequenceClassifier.java:86)
	at edu.stanford.nlp.ie.NERClassifierCombiner.<init>(NERClassifierCombiner.java:136)
	at edu.stanford.nlp.pipeline.NERCombinerAnnotator.<init>(NERCombinerAnnotator.java:91)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.ner(AnnotatorImplementations.java:70)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$44(StanfordCoreNLP.java:498)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getDefaultAnnotatorPool$65(StanfordCoreNLP.java:533)
	at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:118)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:146)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:447)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:146)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:133)
	at de.uni_mannheim.utils.coreNLP.CoreNLPUtils.StanfordDepNNParser(CoreNLPUtils.java:50)
	at de.uni_mannheim.minie.main.Extractor.<init>(Extractor.java:29)
	at de.uni_mannheim.minie.main.Main.main(Main.java:87)
Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: MetaClass couldn't create public edu.stanford.nlp.time.TimeExpressionExtractorImpl(java.lang.String,java.util.Properties) with args [sutime, {}]
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:237)
	at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:382)
	at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:38)
	... 18 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:233)
	... 20 more
Caused by: java.lang.RuntimeException: Error initializing binder 1
	at edu.stanford.nlp.time.Options.<init>(Options.java:92)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.init(TimeExpressionExtractorImpl.java:44)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.<init>(TimeExpressionExtractorImpl.java:39)
	... 25 more
Caused by: java.lang.IllegalStateException: Cannot instantiate configuration.
	at de.jollyday.datasource.impl.XmlFileDataSource.getConfiguration(XmlFileDataSource.java:39)
	at de.jollyday.impl.DefaultHolidayManager.doInit(DefaultHolidayManager.java:239)
	at de.jollyday.HolidayManager.init(HolidayManager.java:319)
	at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:44)
	at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:13)
	at de.jollyday.util.Cache.get(Cache.java:51)
	at de.jollyday.HolidayManager.createManager(HolidayManager.java:168)
	at de.jollyday.HolidayManager.getInstance(HolidayManager.java:148)
	at edu.stanford.nlp.time.JollyDayHolidays.init(JollyDayHolidays.java:57)
	at edu.stanford.nlp.time.Options.<init>(Options.java:90)
	... 27 more
Caused by: java.lang.IllegalStateException: Cannot parse holidays XML file.
	at de.jollyday.util.XMLUtil.unmarshallConfiguration(XMLUtil.java:78)
	at de.jollyday.datasource.impl.XmlFileDataSource.getConfiguration(XmlFileDataSource.java:37)
	... 36 more
Caused by: javax.xml.bind.JAXBException: Provider com.sun.xml.internal.bind.v2.ContextFactory not found
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:148)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:361)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:446)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:409)
	at de.jollyday.util.XMLUtil$JAXBContextCreator.create(XMLUtil.java:170)
	at de.jollyday.util.XMLUtil.unmarshallConfiguration(XMLUtil.java:71)
	... 37 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:573)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:145)
	... 42 more
```

My java version is as follows
```
root@xxx:/xxx/minie/target# java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```

Is it an error caused by the version of Stanford CoreNLP?

**Comment by calbee633810** [comment]
I also tried the second solution and add this to the pom.xml:

```
<plugin>
         <groupId>org.codehaus.mojo</groupId>
         <artifactId>exec-maven-plugin</artifactId>
         <version>1.6.0</version>
         <configuration>
            <mainClass>de.uni_mannheim.minie.main.Main</mainClass>
         </configuration>
      </plugin>
```

Then I use `mvn clean install` and `mvn exec:java` to run the project. However, the same error appears as above. 

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project minie: An exception occured while executing the Java class. Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl: MetaClass couldn't create public edu.stanford.nlp.time.TimeExpressionExtractorImpl(java.lang.String,java.util.Properties) with args [sutime, {}]: InvocationTargetException: Error initializing binder 1: Cannot instantiate configuration. Cannot parse holidays XML file. Provider com.sun.xml.internal.bind.v2.ContextFactory not found -> [Help 1]
```

Could you please give me some hints to solve this problem? Thanks a lot!

**Comment by gkiril** [comment]
See if any of these solves your problem:

1. https://github.com/stanfordnlp/CoreNLP/issues/367

2. https://github.com/stanfordnlp/CoreNLP/issues/594

3. https://stackoverflow.com/questions/42120594/error-creating-edu-stanford-nlp-time-timeexpressionextractorimpl

In general, just google for 
`Exception in thread "main" edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl`

This seems to be some CoreNLP issue (maybe you use different versions of CoreNLP or java; if you have java 9, try with java 8 as well).

**Comment by calbee633810** [comment]
Thanks a lot for the hints! 
https://stackoverflow.com/questions/42120594/error-creating-edu-stanford-nlp-time-timeexpressionextractorimpl works for me.
Changing to java 8 is another feasible solution.

Thanks again for sharing the great project.
:)

**Comment by gkiril** [comment]
I am glad this helps, I hope you will find MinIE useful for your project :)
